org: owenhathaway
app: ohlaw-www
service: ohlaw-www
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  logs:
    restApi: true
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  contact_us: ${file(api/functions/contact_us.yml)}

resources:
  Resources:
    # Web site home bucket
    SiteBucket: ${file(api/resources/site_bucket.yml)}
    #site_bucket_policy: ${file(api/resources/site_bucket_policy.yml)}
    #log_bucket: ${file(api/resources/log_bucket.yml)}
    # CDN Distribution
    cdnDnsRecords: ${file(api/resources/dns_rr_group.yml)}
    #cdnCertificate: ${file(api/resources/cdn_certificate.yml)}
    cdnIdentityConfig: ${file(api/resources/cloudfront_identity.yml)}
    cdnDistribution: ${file(api/resources/cloudfront_distribution.yml)}

    # Email service configuration
    contactTemplate: ${file(api/resources/contact_template.yml)}
    #sesRuleSet: ${file(api/resources/ses_ruleset.yml)}
    #sesRules: ${file(api/resources/ses_rules.yml)}

    # Permissions
    lambdaPermissionToSes: ${file(api/permissions/lambda_permission_to_ses.yml)}
